<?php

namespace Swagger\LaraSwagger\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Http\Response;
use Swagger\LaraSwagger\Swagger\SwaggerGenerator;

/**
 * Swagger controller to access api docs is generated by swagger.
 */
class SwaggerController extends Controller
{

    /**
     * @var SwaggerGenerator
     */
    protected $swaggerGenerator;

    /**
     * SwaggerController constructor.
     *
     * @param SwaggerGenerator $swaggerGenerator
     */
    public function __construct(SwaggerGenerator $swaggerGenerator)
    {
        $this->swaggerGenerator = $swaggerGenerator;
    }

    /**
     * Swagger generate api docs.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->swaggerGenerator->getOption()->setHost($request->getHost());

        $response = new Response($this->swaggerGenerator->generateDocs());

        if (config('swaggeravel.routes.cors')) {
            $response
                ->header('Access-Control-Allow-Methods', 'GET')
                ->header('Access-Control-Allow-Headers', 'Content-Type')
                ->header('Access-Control-Allow-Origin', '*');
        }

        return $response;
    }
}
